Pets/Models/ErrorViewModel.cs
namespace Pets.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pets/Models/Pet.cs
namespace Pets.Models
{
    public class Pet
    {
        public int ID { get; set; }
        public string? Names { get; set; }
        public string? Raza { get; set; }
        public int Edad { get; set; }
        public string? NameOwn { get; set; }

    }
}

Pets/Models/PetsDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace Pets.Models
{
    public class PetsDBContext : DbContext
    {
        public PetsDBContext(DbContextOptions<PetsDBContext> options) 
            : base(options)
        {
            
        }
        public DbSet<Pet> Pet { get; set; }
    }
}

Pets/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pets.Models;
using System.Diagnostics;

namespace Pets.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


    }
}

Pets/Controllers/PetsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Pets.Models;
using Newtonsoft.Json;

namespace Pets.Controllers
{
    public class PetsController : Controller
    {
        private const string PetListCacheKey = "PetList";

        private PetsDBContext BD;

        public PetsController(PetsDBContext context)
        {
            BD = context;
        }

       // private readonly IDistributedCache? _distributedCache;

        //public PetsController(IDistributedCache distributedCache)
        //{
        //    _distributedCache = distributedCache;
        //}

        public IActionResult Index()
        {
            var list = BD.Pet.ToList();
            return View(list);
        }

        [HttpGet]
        public IActionResult NewDate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewDate(Pet pet)
        {
            BD.Pet.Add(pet);
            BD.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Update(int Id)
        {

            var pet = BD.Pet.FirstOrDefault(x => x.ID == Id);

            return View(pet);

        }

        [HttpPost]
        public ActionResult Update(Pet pet)
        {
            var petUpdate = BD.Pet.FirstOrDefault(x => x.ID == pet.ID);

            // Modifyh field to update
            petUpdate.Names = pet.Names;
            petUpdate.Raza = pet.Raza;
            petUpdate.NameOwn = pet.NameOwn;
            petUpdate.Edad = pet.Edad;

            BD.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id) 
        {

            var petDelete = BD.Pet.FirstOrDefault(x => x.ID == id);
            BD.Pet.Remove(petDelete);
            BD.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Pets/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pets/Views/Pets/Index.cshtml
@model List<Pets.Models.Pet>

<h2>
    <a href="@Url.Action("NewDate", "Pets")" class="btn btn-success" style="float:right">New</a>
    Pet List
</h2>
<hr />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Raza</th>
            <th>Age</th>
            <th>Own Name</th>
            <th>Actions</th>
        </tr>
    </thead>
   

    <tbody>
       @foreach (var pet in Model)
        {
            <tr>
                <td>@pet.ID</td>
                <td>@pet.Names</td>
                <td>@pet.Raza</td>
                <td>@pet.Edad</td>
                <td>@pet.NameOwn</td>
                <td>
                    <a href="@Url.Action("Update", "Pets", new{Id = pet.ID})" class="btn btn-primary">Update</a>
                    <a href="@Url.Action("Delete", "Pets", new{Id = pet.ID})" class="btn btn-danger">Drop</a>
                </td>
            </tr>
        }
       
    </tbody>
</table>

Pets/Views/Pets/NewDate.cshtml
@model Pets.Models.Pet

<h2>NewDate</h2>
<hr />

<form action="@Url.Action("NewDate","Pets")" method="post">

    <div class="form-group col-3">
        <labe>ID</labe>
        @Html.TextBoxFor(X => X.ID, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Name</labe>
            @Html.TextBoxFor(X => X.Names, new{ @class="form-control", @required="required" })
     </div>

    <div class="form-group col-3">
        <labe>Raza</labe>
        @Html.TextBoxFor(X => X.Raza, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Age</labe>
        @Html.TextBoxFor(X => X.Edad, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Own Name</labe>
        @Html.TextBoxFor(X => X.NameOwn, new{ @class="form-control", @required="required" })
    </div>

    <div>
        <input type="submit" value="Save" class="btn btn-primary mt-3" />
        <a href="@Url.Action("Index", "Pets")" class="btn btn-danger mt-3">Return</a>
    </div>
     
</form>

Pets/Views/Pets/Update.cshtml
@model Pets.Models.Pet

<h2>Update Pets</h2>
<hr />

<form action="@Url.Action("Update","Pets")" method="post">

    <div class="form-group col-3">
        <labe>ID</labe>
        @Html.TextBoxFor(X => X.ID, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Name</labe>
        @Html.TextBoxFor(X => X.Names, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Raza</labe>
        @Html.TextBoxFor(X => X.Raza, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Age</labe>
        @Html.TextBoxFor(X => X.Edad, new{ @class="form-control", @required="required" })
    </div>

    <div class="form-group col-3">
        <labe>Own Name</labe>
        @Html.TextBoxFor(X => X.NameOwn, new{ @class="form-control", @required="required" })
    </div>

    <div>
        <input type="submit" value="Save" class="btn btn-primary mt-3" />
        <a href="@Url.Action("Index", "Pets")" class="btn btn-danger mt-3">Return</a>
    </div>

</form>

Pets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetsWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pets.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetsWebsite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Pets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PetsWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>